Mobile First Portfolio Project
juaryimami/Hello-Portfolio pull request #1
Opened 2022-08-19 09:26 UTC by juaryimami

I made the first changes on this project please give me a comment. your comments are so important tome

2022-08-19 10:53 UTC, levy002 requested changes
## Hello @juaryimami  , :wave:
### I'm Levy, your PR reviewer

Magnificent 😎 
There are some issues that you still need to work on to go to the next project but you are almost there!

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Highlights
- Linters are green ✔️ 
- Clean code ✔️ 
- Nice design ✔️ 
- Correct Github flow ✔️ 
- Descriptive README ✔️ 
## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._
 - [x] Kindly make sure to set up linters correctly so it runs to check if there are no errors on your pull request. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css) to understand it clearly and follow the guideline to set it correctly. 
 
     ### Make sure style lint is running as expected on Github
 
- [x] Kindly make sure to add a good PR title and PR description. It makes your repo looks more professional. :wink: Kindly go ahead and edit your PR and add a descriptive PR  summary.

   - Example of good PR
![image](https://user-images.githubusercontent.com/87197412/184990532-da778ab4-c789-4136-90a9-629eedd969da.png)
   
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to write your commit message in imperative tense and capitalized it. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:53 UTC, levy002 commented on index.html
> +		<a href="#" class="head__link fz-16 fw-500 lh-24">My Projects</a>
- [ ] Kindly make sure the correct title for this section. Please use `LET'S CONNECT` instead of using `My projects` because this section is for telling the user to connect with you on your social media. :wink:
- [ ] Please make use to use `hx` tags (h1, h2, h3, etc...) while this is the title for all your social media links.

2022-08-19 11:41 UTC, juaryimami commented
In this project:

Added Linters
Added the html file
Styled the Heading 
updated readme file

THANK YOU FOR REVIEWING MY PROJECT!!!!

2022-08-19 11:52 UTC, awais-amjed reviewed
Hi @juaryimami , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, that has the `linters.yml` file modified. Please take a step back and copy the exact `linters.yml` [file](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) from the [linters repository](https://github.com/microverseinc/linters-config/tree/master/html-css) 🤗

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-19 12:42 UTC, emmiiorji approved these changes
Hi @juaryimami, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/185620059-41f2fac2-8b91-40d9-9f29-c5c6a0978af4.gif)


## Highlights

- Implemented all requested changes
- Linter properly set up and passing all checks
- Design well implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 12:47 UTC, merged

2022-08-19 12:47 UTC, juaryimami commented
Thank you!!!!!!

2022-10-11 08:33 UTC, juaryimami commented
Awesome, thanks!

On Fri, 19 Aug 2022, 3:42 pm Emmanuel Orji-Ihuoma, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @juaryimami <https://github.com/juaryimami>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> [image: congratulations]
> <https://user-images.githubusercontent.com/20554583/185620059-41f2fac2-8b91-40d9-9f29-c5c6a0978af4.gif>
> Highlights
>
>    - Implemented all requested changes
>    - Linter properly set up and passing all checks
>    - Design well implemented
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/Hello-Portfolio/pull/1#pullrequestreview-1078760120>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXV7W7D6TRBRNGURE3DVZ56L7ANCNFSM57ACAOTA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>